name: "运行发布命令"
description: "此处确保docker compose已经启动"
inputs:
  cdDir:
    description: "要跳转的目录"
    required: true
    default: "./demo"
  type:
    description: "要模拟的名称"
    required: true
    default: "cjs"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version from tag
      id: extract_version
      uses: ../extractTag
      with:
        tag: ${{ github.ref }} # 传递 GitHub tag

    - name: "Run tests request Docker container ${{ inputs.type }}"
      run: |
        cd "${inputs.cdDir}" || exit 1
        cp ./.npmrc ~/.npmrc
        ls -al ~
        cat ~/.npmrc
        docker ps -a
        node -e "console.log(process.cwd())" & npm run pub --tag ${{steps.extract_version.outputs.npm_tag}} || exit 1
      shell: 'bash'

    - name: Docker compose log with cjs
      if: always() # This ensures it runs regardless of success or failure
      run: |
        docker ps --filter "name=verdaccio" --format "{{.ID}}" | awk '{if ($1) print $1}' | xargs -I {} docker logs {}
      shell: 'bash'
