name: "运行发布命令"
description: "此处确保docker compose已经启动"
inputs:
  cdDir:
    description: "要跳转的目录"
    required: true
    default: "./demo"
  cmd:
    description: "要执行的发布命令"
    default: "npm i && npm publish"
  type:
    description: "要模拟的名称"
    default: "cjs"
runs:
  using: "composite"
  steps:
    - name: "Run tests request Docker container ${{ inputs.type }}"
      run: |
        echo "${{inputs.cdDir}}"
        cd "${{inputs.cdDir}}" || exit 1
        cp ./.npmrc ~/.npmrc
        ls -al ~
        cat ~/.npmrc
        docker ps -a
        node -e "console.log(process.cwd())" & bash -c "${{inputs.cmd}}" || exit 1 #  --tag ${{steps.extract_version.outputs.npm_tag}}
      shell: 'bash'

    - name: "Docker compose log with  ${{ inputs.type }}"
      if: always() # This ensures it runs regardless of success or failure
      run: |
        docker ps --filter "name=verdaccio" --format "{{.ID}}" | awk '{if ($1) print $1}' | xargs -I {} docker logs {}
      shell: 'bash'
