name: "解析npm sevmer 版本中的关键词"
description: "根据tag v0.1.1-alpha.1，发布beta,alpha,latest等关键字的tag标签"
inputs:
  tag:
    description: "github tag"
    required: true
outputs:
  npm_tag:
    description: "需要发布的alpha,beta,latest等标签"
  version:
    description: 不带v前缀的版本号"
runs:
  using: "composite"
  steps:
    - name: Extract version and determine npm tag
      run: |
        TAG="${{ inputs.tag }}"  # 获取 GitHub Tag
        VERSION=${TAG//v/}  # 去掉 "v" 前缀，变成 0.1.1-alpha.1 格式
        echo "Version: $VERSION"

        # Check if the tag contains "alpha" or "beta"
        if [[ "$TAG" == *"-alpha"* ]]; then
          NPM_TAG="alpha"
        elif [[ "$TAG" == *"-beta"* ]]; then
          NPM_TAG="beta"
        else
          NPM_TAG="latest"
        fi

        echo "npm tag: $NPM_TAG"
        echo "::set-output name=version::$VERSION"
        echo "::set-output name=npm_tag::$NPM_TAG"
