name: '运行发布命令'
description: '此处确保docker compose已经启动'
inputs:
  cdDir:
    description: '要跳转的目录'
    required: true
    default: './demo'
  type:
    description: '要模拟的名称'
    required: true
    default: 'cjs'
outputs:
  result:
    description: 'The result of the action'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: "Run tests request Docker container ${{ inputs.type }}"
      run: |
          cd "${inputs.cdDir}" || exit 1
          cp ./.npmrc ~/.npmrc
          ls -al ~
          cat ~/.npmrc
          docker ps -a
          node -e "console.log(process.cwd())" & npm run pub || exit 1
    - name: Docker compose log with cjs
      if: always()  # This ensures it runs regardless of success or failure
      run: |
        docker ps --filter "name=verdaccio" --format "{{.ID}}" | awk '{if ($1) print $1}' | xargs -I {} docker logs {}


