version: "3.0"

services:
  verdaccio_1:
    image: verdaccio/verdaccio:5.32.2
    container_name: verdaccio_1
    environment:
      - DEBUG=*
    volumes:
      - ./storage1:/verdaccio/storage
      # - ./veradaccio-db:/verdaccio/storage/.verdaccio-db.json
      - ./htpasswd:/verdaccio/htpasswd
      - ./config.yaml:/verdaccio/conf/config.yaml
    user: "10001:10001"  # 在容器中指定用户
    ports:
      - "4877:4873"

  verdaccio_2:
    image: verdaccio/verdaccio:5.32.2
    container_name: verdaccio_2
    environment:
      - DEBUG=*
    volumes:
      - ./storage2:/verdaccio/storage
      # - ./veradaccio-db:/verdaccio/storage/.verdaccio-db.json
      - ./config.yaml:/verdaccio/conf/config.yaml
      - ./htpasswd:/verdaccio/htpasswd
      # - ./verdaccio2/storage/:/verdaccio/storage/
      # - ./verdaccio2/plugins/:/verdaccio/plugins/
      # - ./verdaccio2/conf/:/verdaccio/conf/
      # - ./verdaccio2/htpasswd:/verdaccio/htpasswd
    user: "10001:10001"  # 在容器中指定用户
    ports:
      - "4878:4873"

# volumes:
#   verdaccio1:
#     driver: local
#   verdaccio2:
#     driver: local