version: "3.0"

services:
  verdaccio_1:
    image: verdaccio/verdaccio:5.32.2
    container_name: verdaccio_1
    environment:
      - DEBUG=*
    volumes:
      - ./storage1:/verdaccio/storage
      - ./htpasswd:/verdaccio/htpasswd
      - ./config.yaml:/verdaccio/conf/config.yaml
    ports:
      - "4877:4873"

  verdaccio_2:
    image: verdaccio/verdaccio:5.32.2
    container_name: verdaccio_2
    environment:
      - DEBUG=*
    volumes:
      - ./storage2:/verdaccio/storage
      - ./config.yaml:/verdaccio/conf/config.yaml
      - ./htpasswd:/verdaccio/htpasswd
    ports:
      - "4878:4873"
