name: Publish CI

on:
  push:
    tags: 
      - 'v*'

jobs:
  # 暂时不管这个，登录一直失败
  test-publish:
    uses: "./.github/workflows/test.yml"
    with:
      dockerComposeFile: "./docker-file/docker-compose.yaml"

  publish:
    needs: test-publish
    if: success()  # 只有当 'build' 成功时，才执行该作业
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Register Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Authenticate to npm registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lock

      - name: Publish
        run: |
          npm publish