name: Test测试publish功能

on:
  workflow_call:
    inputs:
      dockerComposeFile:
        required: true
        type: string

jobs:
  test-publish-in-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20, 22] # 指定要测试的 Node.js 版本

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: extract_version
        uses: ./.github/actions/extractTag
        with:
          tag: ${{ github.ref }} # 传递 GitHub tag

      - name: Register Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start containers using Docker Compose
        run: |
          sudo chown -R 10001:10001 ./docker-file/storage1
          sudo chown -R 10001:10001 ./docker-file/storage2
          docker-compose -f ${{ inputs.dockerComposeFile }} up -d --build --force-recreate  # 构建并启动容器，`-d` 表示在后台运行

      - name: Install wait-for-it
        run: sudo apt-get install -y wait-for-it

      - name: Wait for services to be ready
        run: |
          # 等待容器完全启动，可以根据你的容器服务进行调整
          wait-for-it  localhost:4877 -t 60
          wait-for-it  localhost:4878 -t 60

      - name: 'Public test lib1'
        uses: ./.github/actions/runPub
        with:
          cdDir: ./demo/lib1
          type: cjs

      - name: 'Public test lib2'
        uses: ./.github/actions/runPub
        with:
          cdDir: ./demo/lib2
          type: esm

      - name: 'Public test npm-workspace'
        uses: ./.github/actions/runPub
        with:
          cdDir: ./demo/npm-workspace
          cmd: 'npm publish --workspaces'

      - name: 'Public test pnpm-workspace'
        uses: ./.github/actions/runPub
        if: ${{ matrix.node-version >= 16 }}
        with:
          cdDir: ./demo/p-workspace
          cmd: 'pnpm -r publish'

      - name: Tear down containers
        run: |
          docker-compose -f ${{ inputs.dockerComposeFile }} down # 停止并清理容器
